<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sonali" failures="0" tests="2" name="TestNGStudy.TimeOutKeywordStudy" time="3.041" errors="1" timestamp="2023-12-30T16:30:41 IST" skipped="0">
  <testcase classname="TestNGStudy.TimeOutKeywordStudy" name="timeOutStudy" time="2.025">
    <system-out>
      <![CDATA[testcase is passed]]>
    </system-out>
  </testcase> <!-- timeOutStudy -->
  <testcase classname="TestNGStudy.TimeOutKeywordStudy" name="timeOutStudy1" time="1.016">
    <error message="Method TestNGStudy.TimeOutKeywordStudy.timeOutStudy1() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNGStudy.TimeOutKeywordStudy.timeOutStudy1() didn't finish within the time-out 1000
at java.base@17.0.8/java.lang.Thread.sleep(Native Method)
at app//TestNGStudy.TimeOutKeywordStudy.timeOutStudy1(TimeOutKeywordStudy.java:16)
at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.8/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.8/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.8/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- timeOutStudy1 -->
  <system-out>
    <![CDATA[testcase is passed]]>
  </system-out>
</testsuite> <!-- TestNGStudy.TimeOutKeywordStudy -->
